### PR TITLE
Repository refactoring and python packaging

### PR DESCRIPTION
**Pull request by mlange05**
This branch renames and reorganises the python components of the propagator repo into a single `opesci` python package. It also includes:

* Move grid3d test and it's model definition to `tests`
* Separate the base classes into individual files
* Make template finding more robust
* Adds `grid.generate(filename)` function that encapsualtes the codegen process
* Add a few syntactic shortcuts, such as generic switch handling
* Compile auto-generated code against central opesci utility libs

### CODE REVIEW

**Comment by ctjacobs** [comment]
Seems fine. Rename "propagator" to "OPESCI-FD" in the `README` too?

**Comment by mlange05** [comment]
Ok, I renamed the test and updated the README to provide a clear and concise example. @tj-sun, can you please have a look and indicate if you are happy with all the changes in this PR?

**Comment by tj-sun** [comment]
Sorry delay, I only saw this earlier today.
- It looks like grid is still using the default (0.1, 0.1, 0.1) spacing even though input is grid_size (100,100,100), i.e. spacing (0.01, 0.01, 0.01). Now grid_size is passed as argument in constructor, I think we need to run set_domain_size() and set_grid_size() at the end of the constructor with the input parameters (if they are not None), so that spacing can be updated.
- I saw that I forgot to change "param spacing" to "param grid_size" in eigentest docstring. So that need to be changed to something like ":param grid_size: define number of grid points, e.g. (10, 10, 10)"

Other than that all looks very good. Particularly the setattr() in grid makes it a lot tidier. (something I googled but gave up half way)

P.S. I'm working on some new re-factoring which should help the free-surface boundary part. I will base it on this after it's merged. Aiming to submit later this week.

**Comment by mlange05** [comment]
@tj-sun, fixed the spacing bug and changed the doc string. The CMakeList in root seems to be used for buildign the `segy2vts` tool, so I think we should leave it.

**Comment by mlange05** [comment]
Ok, merging and renaming the repo now.

**Pull request merged**
